export const ENV = {
  LINKEDIN_API_KEY: process.env.LINKEDIN_API_KEY,
  GOOGLE_MAP_API_KEY: process.env.GOOGLE_MAP_API_KEY,
  LOCAL_API_V1: process.env.LOCAL_API_V1,
  API_V1: process.env.API_V1,
  ACCESS_TOKEN_SECRET_KEY: process.env.ACCESS_TOKEN_SECRET_KEY,
  API_URL: process.env.API_URL,
  SESSION_PASSWORD: process.env.SESSION_PASSWORD,
  COOKIE_NAME: process.env.COOKIE_NAME,
  COOKIE_EXPIRED_TIME: process.env.COOKIE_EXPIRED_TIME,
  NODE_ENV: process.env.NODE_ENV
};